ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views
app_name='cart'
urlpatterns = [
    path('cart/<int:i>',views.add_to_cart,name='cart'),
    path('cart_view/',views.cart_view,name='cart_view'),
    path('add_to_cart/<int:i>',views.add_to_cart,name='add_to_cart'),
    path('cart_decrement/<int:i>',views.cart_decrement,name='cart_decrement'),
    path('remove/<int:i>',views.remove,name='remove'),
    path('place_order',views.place_order,name='place_order'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from .import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from .import views
app_name='search'
urlpatterns = [
    path('search/',views.search_product,name='search')
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from .import views
app_name='shop'
urlpatterns = [
    path('',views.home,name='home'),
    path('category',views.category,name='category'),
    path('product/<int:i>',views.product,name='product'),
    path('details/<int:i>',views.details,name='details'),
    path('register',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout')
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    data_added = models.DateTimeField(auto_now_add=True)

    # def subtotal(self):
    #     return self.quantity*self.product.price

    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price


class Order_table(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items = models.IntegerField
    phone = models.CharField(max_length=30)
    address = models.TextField()
    pin = models.CharField(max_length=30)
    ordered_date = models.DateTimeField(auto_now_add=True)
    order_id = models.CharField(max_length=100,blank=True)
    payment_status = models.CharField(default='pending',max_length=30)
    delivery_status = models.CharField(default='pending',max_length=30)
    def __str__(self):
        return self.user.username

class Payment(models.Model):
    name = models.CharField(max_length=50)
    amount = models.CharField(max_length=50)
    order_id = models.CharField(max_length=50, blank=True)
    razorpay_payment_id = models.CharField(max_length=50, blank=True)
    paid = models.BooleanField(default=False)
    def _str_(self):
        return self.name

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='media/image',blank=True,null=True)
    def __str__(self):
        return self.name
#
class Product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='media/products',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from .models import Product
from .models import Cart,Order_table,Payment
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import razorpay

@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity +=1
            cart.save()
            p.stock -=1
            p.save()
    except:
        if(p.stock):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -=1
            p.save()

    return redirect('cart:cart_view')

def cart_view(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total=total+i.quantity*i.product.price
    return  render(request,'cart.html',{'c':cart,'total':total})

def cart_decrement(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(Cart.quantity>1):
            cart.quantity -=1
            cart.save()
            p.stock+=1
            p.save()
        else:
            cart.delete()
            p.stock +=1
            p.save()
    except:
        pass
    return redirect('cart:cart_view')


def remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        cart.delete()
        p.save()
    except:
        pass
    return redirect('cart:cart_view')

def place_order(request):
    if(request.method=='POST'):
        p = request.POST.get('p')
        a = request.POST.get('a')
        n = request.POST.get('n')
        u = request.user
        c = Cart.objects.filter(user=u)
        total=0
        for i in c:
            total=total+(i.quantity*i.product.price)
            totat=int(total*100)#total amt

            #create razorpay  client using our API credentials

            client = razorpay.Client(auth=('rzp_test_KjG8ydENFtiZ4P','YFjiW3CMX7Z1Pq164lgbzKrm'))

        #create order in razorpay
        response_payment=client.order.create(dict(amount=total,currency='INR'))
        print(response_payment)
        return render(request,'place_order.html')

    return render(request,'place_order.html')

ecommerce/search/views.py
from django.shortcuts import render

from shop.models import Product
from django.db.models import Q
def search_product(request):
    p=None
    qurey=''
    if(request.method=='POST'):
        query=request.POST['q']
        if query:
            p=Product.objects.filter(Q(name__icontains=query)|Q(desc__icontains=query))
            return render(request,'search.html',{'p':p})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from .models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.http import HttpResponse
from  django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request,'home.html')

def category(request):
    item=Category.objects.all()

    return render(request,'category.html',{'item':item})

def product(request,i):
    c=Category.objects.get(id=i)
    p=Product.objects.filter(category=c)
    item=Product.objects.all()
    return render(request,'product.html',{'c':c,'p':p})

def details(request,i):
    d=Product.objects.get(id=i)
    return render(request,'details.html',{'d':d})
@login_required()
def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        e = request.POST['e']
        fn = request.POST['fn']
        ln = request.POST['ln']
        if (cp == p):
            user = User.objects.create_user(username=u, password=p, email=e, first_name=fn, last_name=ln)
            user.save()
            return redirect('home')

    return render(request,'register.html')

def user_login(request):
    if (request.method == 'POST'):
        u = request.POST['u']
        p = request.POST['p']
        user = authenticate(username=u, password=p)
        if user:
            login(request, user)
            return redirect('shop:home')
        else:
            messages.error(request, 'Invalid Credentials')

    return render(request, 'login.html')


def user_logout(request):
    logout(request)
    return redirect('shop:user_login')

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="row">
		<div class="col-7">
			<div class="container mt-5 pt-5">
				<table class="table table-bordered">
					<tr>
						<th>Cart Items</th>
					</tr>
					{% for i in c %}
					<tr>
						<td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
						<td>{{i.product.name}}</td>
						<td>{{i.product.id}}</td>
						<td>{{i.quantity}} <br> Unit Price:{{i.product.price}}</td>
						<td>{{i.subtotal}}</td>
						<td>
							{% if i.product.stock > 0 %}
							<a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-plus"></i></a> <br>
							<a href="{% url 'cart:cart_decrement' i.product.id %}"><i class="fa-solid fa-minus"></i></a> <br>
							<a href="{% url 'cart:remove' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
		<div class="col-5">
			<div class="container mt-5 pt-5">
				<table class="table table-bordered" style="width:50%;">
					<tr>
						<th>CheckOut</th>
					</tr>
					<tr>
						<th>Total Amount :{{total}} </th>
					</tr>
				</table>
				<a href="{% url 'cart:place_order' %}" class="btn stext-103 cl2 size-102 bg1 bor2 hov-btn1 p-lr-15 trans-04" style="background-color:green;color-white"><b>Place Order</b></a>
				<a href="{% url 'shop:home' %}" class="btn stext-103 cl2 size-102 bg1 bor2 hov-btn1 p-lr-15 trans-04" style="background-color:blue;color:white"><b>Continue Shopping</b></a>
			</div>
		</div>

	</div>



{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Single gallery Item Start -->
                    <div class=" row col-4 single_gallery_item shoes wow fadeInUpBig" data-wow-delay="0.5s">
                        {% for i in item %}
                        <!-- Product Image -->
                        <div class="product-img">
                            <img src="{{i.image.url}}" alt="">
                            <div class="product-quicview">
                                <a href="#" data-toggle="modal" data-target="#quickview"><i class="#"></i></a>
                            </div>
                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            <h4 class="product-price">{{i.price}}</h4>
                            <p>{{i.desc}}</p>
                            <!-- Add to Cart -->
                            <a href="{% url 'shop:product' i.id %}" class="add-to-cart-btn">MORE ITEMS</a>
                        </div>
                        {% endfor %}
                  </div>



{% endblock %}

ecommerce/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Single gallery Item Start -->
                    <div class="col-4 col-sm-6 col-md-4 single_gallery_item shoes wow fadeInUpBig"  data-wow-delay="0.5s">


                        <!-- Product Image -->
                        <div class="product-img">
                            <img src="{{d.image.url}}"  style="height=150px; width=100% alt="">
                            <div class="product-quicview">
                                <a href="#" data-toggle="modal" data-target="#quickview"><i class="ti-plus"></i></a>
                            </div>
                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            <h4 class="product-price">{{d.price}}</h4>
                            {% if d.stock > 0 %}
                                <h4>Stock Avaliable,{{d.stock}}</h4>
                            {% else %}
                            <h4>stock unavaliable</h4>
                            {% endif %}
                            <p>{{d.desc}}</p>
                            <!-- Add to Cart -->
                            <a href="{% url 'cart:cart' d.id %}" class="add-to-cart-btn">ADD CART</a>
                        </div>
                  </div>



{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Login</title>
<link rel="icon" href="{% static 'img/box-arrow-right.svg' %}" type="image/x-icon">
    {% endblock %}
{% block content %}
<h2>Login Page</h2>
<form class="container" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">User Name</label>
      <input type="text" class="form-control" name="u" id="exampleFormControlInput1" placeholder="Enter Name">
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Password</label>
      <input type="password" class="form-control" name="p" id="exampleFormControlInput2" placeholder="Enter Password">
    </div>
    <div class="mb-3">
        <input type="submit" value="login" class="form-control" style="background-color: green">

    </div>

</form>
{%  if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

ecommerce/templates/logout.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Logout</title>
<link rel="icon" href="{% static 'img/box-arrow-right.svg' %}" type="image/x-icon">
    {% endblock %}
{% block content %}
<h2>Logout Page</h2>
{% endblock %}
</body>
</html>

ecommerce/templates/place_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-6">
					<div class="login_form_inner">
						<h3>Enter Details</h3>
						<form class="row login_form" action="" method="post" id="contactForm" novalidate="novalidate">
							{% csrf_token %}
							<div class="col-md-12 form-group">
								<input type="number" class="form-control"  name="p" placeholder="Phone No" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control"  name="a" placeholder="Delivery Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
							<div class="col-md-12 form-group">
								<input type="text" class="form-control"  name="n" placeholder="pin" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
<!--							<div class="col-md-12 form-group">-->
<!--								<div class="creat_account">-->
<!--									<input type="checkbox" id="f-option2" name="selector">-->
<!--									<label for="f-option2">Keep me logged in</label>-->
<!--								</div>-->
<!--							</div>-->
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="primary-btn">Submit</button>
							</div>
							<div>
								{% if messages %}
									<ul class="messages">
    									{% for message in messages %}
    										<li style="color:red;">{{ message }}</li>
    									{% endfor %}
									</ul>
								{% endif %}
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>


{% endblock %}

ecommerce/templates/product.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Single gallery Item Start -->
<div class="row">
    {% for i in p %}
                    <div class="col-4 col-sm-6 col-md-4 single_gallery_item shoes wow fadeInUpBig" data-wow-delay="0.5s "  ">

                        <!-- Product Image -->
                        <div class="product-img">
                            <img  src="{{i.image.url}} "style="height=150px; width=100% alt="">
                            <div class="product-quicview">
                                <a href="#" data-toggle="modal" data-target="#quickview"><i class="ti-plus"></i></a>
                            </div>
                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            <h4 class="product-price">{{i.name}}</h4>

<!--                            <p>{{i.desc}}</p>-->
                            <!-- Add to Cart -->
                            <a href="{% url 'shop:details' i.id %}" class="add-to-cart-btn">KNOW MORE</a>
                        </div>

                  </div>
{% endfor %}
</div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Register</title>
    {% endblock %}
{% block content %}
<h2>Register Page</h2>
<form class="container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label  class="form-label">User Name</label>
      <input type="text" class="form-control" name="u"  placeholder="Enter Name">
    </div>
    <div class="mb-3">
      <label  class="form-label">Password</label>
      <input type="password" class="form-control" name="p" id="exampleFormControlInput2" placeholder="Enter Password">
    </div>
    <div class="mb-3">
      <label  class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="cp" placeholder="Confirm Password">
    </div>
    <div class="mb-3">
      <label  class="form-label">First Name</label>
      <input type="text" class="form-control" name="fn" placeholder="Enter First Name">
    </div>
    <div class="mb-3">
      <label  class="form-label">Last Name</label>
      <input type="text" class="form-control" name="ln" placeholder="Enter Last Name">
    </div>
    <div class="mb-3">
      <label  class="form-label">e-mail Id </label>
      <input type="text" class="form-control" name="e" placeholder="Enter E-Mail Id">
    </div>
    <div class="mb-3">
        <input type="submit"class="form-control">

    </div>

</form>
{% endblock %}
</body>
</html>

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Single gallery Item Start -->
<div class="row">
    {% for i in p %}
                    <div class="col-4 col-sm-6 col-md-4 single_gallery_item shoes wow fadeInUpBig" data-wow-delay="0.5s "  ">

                        <!-- Product Image -->
                        <div class="product-img">
                            <img  src="{{i.image.url}} "style="height=150px; width=100% alt="">
                            <div class="product-quicview">
                                <a href="#" data-toggle="modal" data-target="#quickview"><i class="ti-plus"></i></a>
                            </div>
                        </div>
                        <!-- Product Description -->
                        <div class="product-description">
                            <h4 class="product-price">{{i.name}}</h4>
<!--                            <p>{{i.desc}}</p>-->
                            <!-- Add to Cart -->
                            <a href="{% url 'shop:product' i.id %}" class="add-to-cart-btn">KNOW MORE</a>
                        </div>

                  </div>
{% endfor %}
</div>

{% endblock %}

    </div>

</div>